name: CI

on: [push, pull_request]

jobs:
  build_and_lint:
    runs-on: windows-latest
    steps:
      - name: Checkout the repository
        uses: actions/checkout@v5

      - name: Setup Rust
        uses: actions-rust-lang/setup-rust-toolchain@v1
        with:
          components: clippy,rustfmt

      - name: Check build
        run: cargo check --target x86_64-pc-windows-msvc

      - name: Check formatting
        run: cargo fmt --check

      - name: Check lint
        run: cargo clippy -- -D warnings

  discord:
    name: Discord Failure Notification
    needs: [build_and_lint]
    if: failure()
    runs-on: ubuntu-latest
    steps:
      - uses: sarisia/actions-status-discord@v1
        with:
          webhook: ${{ secrets.DISCORD_WEBHOOK }}
          status: failure
          title: ""
